### ISSUE TITLE
잘 만드셨습니다. 하나더 요청 드립니다. :)

### ISSUE THREAD

**Issue by YoungsoonLee** [h4wldev/Frest#4]
굉장히 잘 만드셔서 참고를 많이 하고 있습니다. ^^
flask는 blocking microservice 이기 때문에 non-blocking과 함께 사용 하기를 권장 하고 있는데요...
gunicorn으로 사용 가능 하도록 하게 하는 것도 좋을 것 같습니다. ^^

http://flask.pocoo.org/docs/0.12/deploying/wsgi-standalone/

**Comment by h4wldev** [comment]
좋은 의견 감사합니다! :)
